version: '2'
services:
  odisseia-app:
    image: odisseia
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://odisseia-mysql:3306/odisseia?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://odisseia-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://odisseia-elasticsearch:9200
    ports:
      - 8080:8080
  odisseia-mysql:
    extends:
      file: mysql.yml
      service: odisseia-mysql
  odisseia-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: odisseia-elasticsearch
